[mypy]
python_version = 3.10
ignore_missing_imports = True
warn_return_any = True

[mypy-sklearn.*]
ignore_errors = True

[mypy-cvxpy.*]
follow_imports = skip
follow_imports_for_stubs = true

[mypy-doc.*]
ignore_errors = True

[mypy-torch.*]
follow_imports = skip
ignore_errors = True