sonar.projectKey=p16-mapie
sonar.projectName=MAPIE
sonar.sourceEncoding=UTF-8

sonar.sources=mapie
sonar.tests=mapie/tests
sonar.exclusions=mapie/tests/**

sonar.python.version=3.10,3.11,3.12,3.13
