name: mapie-doc
channels:
    - defaults
    - conda-forge
dependencies:
    - numpydoc=1.1.0
    - pandas=1.2.1
    - python=3.9.2
    - scikit-learn=0.24.1
    - scipy=1.6.1
    - sphinx=3.5.3
    - sphinx-gallery=0.8.2
    - sphinx_rtd_theme=0.5.2
    - typing_extensions=3.7.4