name: Documentation tests

on:
  push:
    branches:
      -dev
      -main
      -master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.doc.txt

      - name: Test doc
        run: cd doc && make doctest
